aliases:
  - &bundle_install
    name: Execute `bundle install`
    command: bundle install
  - &install_cocoapods
    name: Install CocoaPods
    command: pod install
version: 2
jobs:
  build:
    macos:
      xcode: "10.3.0"
    steps:
      - checkout
      - run: *bundle_install
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: SDRlingTests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
